spark:
    master_url: "spark://100.71.201.92:7077"
    deploy_mode: "client"
    driver_host: "100.71.201.92"
    driver_bind_address: "0.0.0.0"
    driver_port: 10000
    block_manager_port: 10001
    app_ui_port: 4040

minio:
    endpoint: "http://100.64.236.51:9000"
    access_key_env: "MINIO_ACCESS_KEY"
    secret_key_env: "MINIO_SECRET_KEY"
    bucket_name: "airtel-spark"
    path_style_access: true
    ssl_enabled: false

iceberg:
    catalog_name: "telecom"
    warehouse_location: "s3a://airtel-spark/warehouse/iceberg"

hive:
    metastore_uri: "thrift://100.64.236.51:9083"
    warehouse_location: "s3a://airtel-spark/warehouse/hive"

storage:
    raw: "s3a://airtel-spark/raw"
    checkpoints: "s3a://airtel-spark/checkpoints"
    models: "s3a://airtel-spark/models"